# Configuraci贸n general
app_name: "Mi Aplicaci贸n"
version: "1.0.0"

# Configuraci贸n de la base de datos
database:
  host: "localhost"
  port: 5432
  user: "admin"
  password: "secreto"
  name: "mi_base_de_datos"

# Configuraci贸n del servidor
server:
  host: "0.0.0.0"
  port: 8000
  debug: true

# Otras configuraciones
logging:
  level: "INFO"
  file: "app.log"